exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=DiffuseWithAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Objects/natural/trees/white_fir/white_fir_leaves_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/ground_plants/heather/heather.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/ground_plants/heather/heather_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Normalmap_lowQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/Ivys/Vines_ddn.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/veg_ivy/ivy_1_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/veg_ivy/ivy_1_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/veg_ivy/ivy_2_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Objects/natural/vegetation/veg_ivy/ivy_2_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Objects/structures/RangerTower/textures/Tower_Plaster_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Specular_lowQ /reduce="pc:1,ps3:1,ps4:-1,wiiu:1,x360:1,xboxone:-1" /ser=0" "D:/Perforce/GameSDK/Objects/structures/Residential/The_Last_House/Textures/TLH/test Spec.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/architecture/roof/rooftiles_black_dif.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/concrete/concrete_rectanglepanel_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/decals/Pine_Needles/PineNeedlesBig_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/decals/Pine_Needles/PineNeedlesBig_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=DisplacementMap /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/decals/Pine_Needles/PineNeedlesBig_displ.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=MergedDetailMap /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/decals/RockyDirt/DirtPebbles_detail.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/decals/RockyDirt/Pebbles_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Normalmap_lowQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/detail_bumpmaps/concrete/concrete_07_detailbump_ddn.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Normalmap_lowQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/detail_bumpmaps/stone/stone_01_detailbump_ddn.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=DiffuseWithAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/fabric/cloth_pack_01_dif.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=DiffuseWithAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/fabric/cloth_pack_02_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/generic/Tiles/Tile_Floor_Ruined_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/metal/metal_1_PBR_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Asphalt/Asphalt_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=TerrainDiffuseHighPassed /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Asphalt/Asphalt_diff.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/detail/grass_moss_PBR_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/RiverBed/RiverBed_Ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=MergedDetailMap_HighQ /reduce=2 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/RiverBed/RiverBed_Detail.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Sand/SandPatch_Ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=MergedDetailMap_HighQ /reduce=2 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Sand/SandPatch_Detail.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Sand/SandRocks1_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=MergedDetailMap_HighQ /reduce=2 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Sand/SandRocks1_detail.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=0 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Sand/SandRocks2_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /mipgentype=gauss /preset=MergedDetailMap_HighQ /reduce=2 /ser=0" "D:/Perforce/GameSDK/Textures/terrain/Sand/SandRocks2_detail.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/vegitation/Moss/Moss_soft_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/Wood/house_textures/wood_paintedcracked.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/Wood/house_textures/wood_paintedcracked_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/Wood/house_textures/wood_paintedcracked_red.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=NormalmapWithGlossInAlpha_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/Wood/house_textures/wood_painted_ddna.tif"
exiftool.exe -SpecialInstructions="/autooptimizefile=0 /preset=Diffuse_highQ /reduce=1 /ser=0" "D:/Perforce/GameSDK/Textures/Wood/house_textures/wood_painted_scraped.tif"
