def main():
    xmls = [
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_acfrontback_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_acfrontback_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_acfrontback_camo1.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_acfrontback_camo2.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_acfrontback_camo3.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_acfrontback_camo4.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_aclogofrontacback_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_aclogofrontacback_blue5.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_aclogofrontacback_camo1.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_aclogofrontacback_camo2.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_aclogofrontacback_camo3.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_aclogofrontacback_camo4.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_crytekfront_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_crytekfront_brown.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_crytekfront_camo1.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_crytekfront_camo2.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_crytekfront_camo3.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_crytekfront_camo4.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_dopefishfront_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_dopefishfront_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_dopefishfront_green.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_dopefishfront_orange.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_dopefishfront_pink.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_dopefishfront_red.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_eilogo_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_eilogo_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_eilogo_khaki.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_eilogo_pink.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_firefrontback_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_firefrontback_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_flagfrontback_pink_camo1.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_flagfrontback_pink_camo2.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_flagfrontback_pink_camo3.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_flagfrontback_pink_camo4.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_nobranding_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_nobranding_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_nobranding_green.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_nobranding_orange.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_nobranding_pink.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_nobranding_red.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_policefrontback_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_policefrontback_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_policefrontback_camo1.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_policefrontback_camo2.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_policefrontback_camo3.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_policefrontback_camo4.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_polycountfront_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_polycountfront_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_polycountfront_pink.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_usfrontback_black.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_usfrontback_blue.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_usfrontback_green.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_usfrontback_orange.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_usfrontback_pink.xml",
        "d:/perforce/dev/GameSDK/Scripts/Entities/Items/XML/clothing/hat/flexcap_usfrontback_red.xml",
    ]
    mtls = [
        "objects/characters/players/generic/hat/flexcap/flexcap_acfrontback_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_acfrontback_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_acfrontback_camo1",
        "objects/characters/players/generic/hat/flexcap/flexcap_acfrontback_camo2",
        "objects/characters/players/generic/hat/flexcap/flexcap_acfrontback_camo3",
        "objects/characters/players/generic/hat/flexcap/flexcap_acfrontback_camo4",
        "objects/characters/players/generic/hat/flexcap/flexcap_aclogofrontacback_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_aclogofrontacback_blue5",
        "objects/characters/players/generic/hat/flexcap/flexcap_aclogofrontacback_camo1",
        "objects/characters/players/generic/hat/flexcap/flexcap_aclogofrontacback_camo2",
        "objects/characters/players/generic/hat/flexcap/flexcap_aclogofrontacback_camo3",
        "objects/characters/players/generic/hat/flexcap/flexcap_aclogofrontacback_camo4",
        "objects/characters/players/generic/hat/flexcap/flexcap_crytekfront_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_crytekfront_brown",
        "objects/characters/players/generic/hat/flexcap/flexcap_crytekfront_camo1",
        "objects/characters/players/generic/hat/flexcap/flexcap_crytekfront_camo2",
        "objects/characters/players/generic/hat/flexcap/flexcap_crytekfront_camo3",
        "objects/characters/players/generic/hat/flexcap/flexcap_crytekfront_camo4",
        "objects/characters/players/generic/hat/flexcap/flexcap_dopefishfront_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_dopefishfront_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_dopefishfront_green",
        "objects/characters/players/generic/hat/flexcap/flexcap_dopefishfront_orange",
        "objects/characters/players/generic/hat/flexcap/flexcap_dopefishfront_pink",
        "objects/characters/players/generic/hat/flexcap/flexcap_dopefishfront_red",
        "objects/characters/players/generic/hat/flexcap/flexcap_eilogo_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_eilogo_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_eilogo_khaki",
        "objects/characters/players/generic/hat/flexcap/flexcap_eilogo_pink",
        "objects/characters/players/generic/hat/flexcap/flexcap_firefrontback_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_firefrontback_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_flagfrontback_pink_camo1",
        "objects/characters/players/generic/hat/flexcap/flexcap_flagfrontback_pink_camo2",
        "objects/characters/players/generic/hat/flexcap/flexcap_flagfrontback_pink_camo3",
        "objects/characters/players/generic/hat/flexcap/flexcap_flagfrontback_pink_camo4",
        "objects/characters/players/generic/hat/flexcap/flexcap_nobranding_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_nobranding_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_nobranding_green",
        "objects/characters/players/generic/hat/flexcap/flexcap_nobranding_orange",
        "objects/characters/players/generic/hat/flexcap/flexcap_nobranding_pink",
        "objects/characters/players/generic/hat/flexcap/flexcap_nobranding_red",
        "objects/characters/players/generic/hat/flexcap/flexcap_policefrontback_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_policefrontback_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_policefrontback_camo1",
        "objects/characters/players/generic/hat/flexcap/flexcap_policefrontback_camo2",
        "objects/characters/players/generic/hat/flexcap/flexcap_policefrontback_camo3",
        "objects/characters/players/generic/hat/flexcap/flexcap_policefrontback_camo4",
        "objects/characters/players/generic/hat/flexcap/flexcap_polycountfront_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_polycountfront_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_polycountfront_pink",
        "objects/characters/players/generic/hat/flexcap/flexcap_usfrontback_black",
        "objects/characters/players/generic/hat/flexcap/flexcap_usfrontback_blue",
        "objects/characters/players/generic/hat/flexcap/flexcap_usfrontback_green",
        "objects/characters/players/generic/hat/flexcap/flexcap_usfrontback_orange",
        "objects/characters/players/generic/hat/flexcap/flexcap_usfrontback_pink",
        "objects/characters/players/generic/hat/flexcap/flexcap_usfrontback_red",
    ]
    for idx, xml in enumerate(xmls):
        with open("d:/perforce/dev/EI/Tools/Scripts/templatexml.xml", "r") as f:
            template = f.read()
            # replace the item name
            template = template.replace(r"%%item_name%%", mtls[idx].split("/")[-1])
            # replace the mtl name with the extension
            template = template.replace(r"%%mtl_name%%", mtls[idx] + ".mtl")
            # replace the mtl without the extension
            template = template.replace(r"%%mtl_name_noext%%", mtls[idx])
        with open(xml, "w") as f:
            f.write(template)


if __name__ == "__main__":
    main()
